import { AbVariant } from "./types";

export const abVariants: AbVariant[] = [
  // Test 1 variants
  {
    id: "var-1-a",
    groupId: "test-1",
    label: "A",
    name: "Control – existing hero",
    description: "Current hero section with 'Start your free trial' messaging",
    isControl: true,
    createdAt: "2025-04-05T10:00:00Z",
    trafficAllocation: 50,
    impressions: 12450,
    uniqueUsers: 11200,
    conversions: 710,
    conversionRate: 5.7,
    liftVsControl: 0,
    pValue: null,
    status: "control",
    trafficSource: "api",
    impressionsSource: "api",
    conversionsSource: "api",
    conversionRateSource: "api",
    notes: "Baseline performance consistent with historical data"
  },
  {
    id: "var-1-b",
    groupId: "test-1",
    label: "B",
    name: "Value-focused hero",
    description: "Hero emphasizing '3x faster workflow' and specific outcomes",
    isControl: false,
    createdAt: "2025-04-05T10:00:00Z",
    trafficAllocation: 50,
    impressions: 12380,
    uniqueUsers: 11150,
    conversions: 805,
    conversionRate: 6.5,
    liftVsControl: 14.0,
    pValue: 0.03,
    status: "running",
    trafficSource: "api",
    impressionsSource: "api",
    conversionsSource: "api",
    conversionRateSource: "api",
    notes: "Strong performance on mobile. Desktop conversion similar to control."
  },
  
  // Test 2 variants (completed)
  {
    id: "var-2-a",
    groupId: "test-2",
    label: "A",
    name: "Control – 5-step flow",
    description: "Original onboarding with 5 steps including company size and use case",
    isControl: true,
    createdAt: "2025-03-15T10:00:00Z",
    trafficAllocation: 50,
    impressions: 4544,
    uniqueUsers: 4320,
    conversions: 3181,
    conversionRate: 70.0,
    liftVsControl: 0,
    pValue: null,
    status: "control",
    trafficSource: "api",
    impressionsSource: "api",
    conversionsSource: "api",
    conversionRateSource: "api"
  },
  {
    id: "var-2-b",
    groupId: "test-2",
    label: "B",
    name: "Streamlined – 3-step flow",
    description: "Simplified onboarding removing non-essential fields",
    isControl: false,
    createdAt: "2025-03-15T10:00:00Z",
    trafficAllocation: 50,
    impressions: 4598,
    uniqueUsers: 4370,
    conversions: 3806,
    conversionRate: 82.8,
    liftVsControl: 18.3,
    pValue: 0.001,
    status: "completed",
    trafficSource: "api",
    impressionsSource: "api",
    conversionsSource: "api",
    conversionRateSource: "api",
    notes: "Clear winner. Reduced friction significantly improved completion."
  },
  
  // Test 3 variants (planned - no data yet)
  {
    id: "var-3-a",
    groupId: "test-3",
    label: "A",
    name: "Control – current payment page",
    description: "Existing payment page design",
    isControl: true,
    createdAt: "2025-04-12T10:00:00Z",
    trafficAllocation: 50,
    impressions: null,
    uniqueUsers: null,
    conversions: null,
    conversionRate: null,
    liftVsControl: null,
    pValue: null,
    status: "control",
    trafficSource: "manual",
    impressionsSource: "manual",
    conversionsSource: "manual",
    conversionRateSource: "manual"
  },
  {
    id: "var-3-b",
    groupId: "test-3",
    label: "B",
    name: "Redesigned with trust signals",
    description: "New design with security badges, testimonials, and clearer pricing breakdown",
    isControl: false,
    createdAt: "2025-04-12T10:00:00Z",
    trafficAllocation: 50,
    impressions: null,
    uniqueUsers: null,
    conversions: null,
    conversionRate: null,
    liftVsControl: null,
    pValue: null,
    status: "running",
    trafficSource: "manual",
    impressionsSource: "manual",
    conversionsSource: "manual",
    conversionRateSource: "manual",
    notes: "Design emphasizes trust and transparency"
  }
];
