import { ExperimentSuggestion } from "./types";

export const experimentSuggestions: ExperimentSuggestion[] = [
  {
    id: "suggestion-1",
    funnelId: "funnel-1",
    segmentId: "segment-1",
    stepName: "Signup started",
    name: "Simplify mobile signup form",
    hypothesis: "Reducing form fields from 6 to 3 will decrease friction and improve signup completion on mobile",
    experimentType: "UX flow",
    primaryMetric: "signup_completion_rate",
    guardrailMetrics: ["email_verification_rate", "signup_quality_score"],
    impact: "High",
    confidence: "High",
    effort: "Low",
    priority: "P0",
    rationale: "Paid search mobile has 43% drop-off at signup. Mobile users expect quick, minimal forms. Industry benchmarks show 3-field forms convert 25% better.",
    status: "Suggested"
  },
  {
    id: "suggestion-2",
    funnelId: "funnel-2",
    segmentId: null,
    stepName: "Day 7 active",
    name: "Add payment prompt at day 5",
    hypothesis: "Introducing payment options earlier (day 5 vs day 7) will increase trial-to-paid conversion",
    experimentType: "Timing",
    primaryMetric: "trial_to_paid_conversion_rate",
    guardrailMetrics: ["trial_churn_rate", "user_satisfaction_score"],
    impact: "High",
    confidence: "Medium",
    effort: "Medium",
    priority: "P0",
    rationale: "63% drop-off from day 7 to paid. Users who engage by day 5 are likely committed. Early payment prompts may capture high-intent users before they disengage.",
    status: "Suggested"
  },
  {
    id: "suggestion-3",
    funnelId: "funnel-1",
    segmentId: "segment-2",
    stepName: "Email verified",
    name: "Show social proof on verification page",
    hypothesis: "Displaying customer testimonials and usage stats on email verification page will increase activation",
    experimentType: "Social proof",
    primaryMetric: "activation_rate",
    guardrailMetrics: ["email_verification_time", "bounce_rate"],
    impact: "Medium",
    confidence: "Medium",
    effort: "Low",
    priority: "P1",
    rationale: "20% drop-off at email verification. Organic desktop users are research-oriented. Social proof can build trust during the verification wait time.",
    status: "Suggested"
  },
  {
    id: "suggestion-4",
    funnelId: "funnel-3",
    segmentId: null,
    stepName: "Profile setup",
    name: "Make profile setup optional",
    hypothesis: "Allowing users to skip profile setup will reduce onboarding friction and increase completion",
    experimentType: "UX flow",
    primaryMetric: "onboarding_completion_rate",
    guardrailMetrics: ["profile_completion_rate", "7_day_retention"],
    impact: "Medium",
    confidence: "Low",
    effort: "Low",
    priority: "P1",
    rationale: "20% drop-off at profile setup. Users may want to explore the product before committing personal information. Can collect data later through contextual prompts.",
    status: "Suggested"
  },
  {
    id: "suggestion-5",
    funnelId: "funnel-2",
    segmentId: "segment-3",
    stepName: "Day 3 engaged",
    name: "Send referrer success notification",
    hypothesis: "Notifying referrers when their referrals activate will improve referred user engagement",
    experimentType: "Messaging",
    primaryMetric: "day_3_engagement_rate",
    guardrailMetrics: ["referrer_satisfaction", "viral_coefficient"],
    impact: "Low",
    confidence: "Medium",
    effort: "Medium",
    priority: "P2",
    rationale: "Referral users have 40% drop-off at day 3. Social dynamics matter for referrals. Referrer engagement may motivate referred users to stay active.",
    status: "Suggested"
  }
];
